### ISSUE TITLE
$wp_fields->add_field() arguments for Named (Post Types, Taxonomies) vs Non-named objects (Settings, User, etc)

### ISSUE THREAD

**Issue by quasel** [sc0ttkclark/wordpress-fields-api#10]
lets use the issue to discuss ideas - the conversation gets lost a bit on slack

> $wp_fields->add_field( ‘object_type’, ‘field_id’, array( … ) );` 
> is current usage (as per Customizer base implementation)
> sc0ttkclark

but for e.g post, taxonomy..  we need to add the "actual type"
my suggestion would be to use an "configuration" array or object?
```php
$wp_fields->add_field(
	array(
		'object' => 'post_type',
		'type'    => 'my_custom_post_type',
		'id'        => 'field_id'
	),
	array( ... ) );
```

this is better than add it as another parameter which needs to be NULL for e.g. user

**Comment by sc0ttkclark** [comment]
Just wanted to list a few options to consider (not that I'm set on any of them:


```php
// 4 argument method, second argument null or same as first argument for non-named objects
$wp_fields->add_field( 'post_type', 'my_custom_post_type', 'my_custom_field', array( ... ) );
$wp_fields->add_field( 'customizer', 'customizer', 'my_option_name', array( ... ) );

// Object name arrays
$wp_fields->add_field( array( 'post_type', 'my_custom_post_type' ), 'my_custom_field', array( ... ) );
$wp_fields->add_field( 'customizer', 'my_option_name', array( ... ) );

// Object name in args
$wp_fields->add_field( 'post_type', 'my_custom_field', array( 'type' => 'my_custom_post_type', ... ) );
$wp_fields->add_field( 'customizer', 'my_option_name', array( ... ) );
```

**Comment by sc0ttkclark** [comment]
I'd like to get some feedback / direction from @helenhousandi on this, assigning to her for now.

**Comment by sc0ttkclark** [comment]
CMB2 and some others just use pure array args instead of any parameters:

https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php#L80

We could consider that as well, it's also more clear and concise what things are for.

So that adds a couple more choices:

```php
// Require object type, parameters for everything else
$wp_fields->add_field( 'post_type', array( 'type' => 'my_custom_post_type', 'id' => 'my_custom_field', ... ) );
$wp_fields->add_field( 'customizer', array( 'id' => 'my_option_name', ... ) );

// Array-only parameters
$wp_fields->add_field( array( 'object' => 'post_type', 'type' => 'my_custom_post_type', 'id' => 'my_custom_field', ... ) );
$wp_fields->add_field( array( 'object' => 'customizer', 'id' => 'my_option_name', ... ) );
```

Again, none of this changes existing implementations, the Customizer sits on top of this and calling the normal Customizer API still works as it does.

**Comment by daggerhart** [comment]
I agree with the 1 array approach being more clear. 

Additionally, it'd be nice to have a method for adding multiple fields to make writing very complex forms a little more bearable.  This would be a bit easier to implement with a single array of arguments.

```php
// add multiple fields with one method call. 
$wp_fields->add_fields(array(
   array( 'object' => 'post_type', 'type' => 'my_custom_post_type', 'id' => 'my_custom_field', ... ),
   array( 'object' => 'post_type', 'type' => 'my_custom_post_type', 'id' => 'my_custom_field2', ... ), 
));
```

**Comment by sc0ttkclark** [comment]
I definitely don't want multiple fields being added in add_field() so a separate add_fields would be good there, though I feel that this format would be better modeling:

```php
// add multiple fields with one method call. 
$wp_fields->add_fields( array(
    'object' => 'post_type',
    'type' => 'my_custom_post_type',
    'fields' => array(
        array( 'id' => 'my_custom_field', ... ),
        array( 'id' => 'my_custom_field2', ... )
    )
) );
```

**Comment by sc0ttkclark** [comment]
We should break out add_fields() into it's own issue and not crowd this one too much :)

**Comment by dan-westall** [comment]
I like the "Require object type, parameters for everything else" because this style already in use

```php
register_post_type(  'book',  array(  'public' => true, 'label'  => 'Books'  )  );
```

**Comment by sc0ttkclark** [comment]
My vote is on the require object type and ID, and everything else in params currentl

**Comment by sc0ttkclark** [comment]
I'll move forward on that today/tonight

**Comment by sc0ttkclark** [comment]
Implemented this in the codebase last night and now it's unit tested against :)
