### ISSUE TITLE
Contributors section

### ISSUE THREAD

**Issue by codearachnid** [sc0ttkclark/wordpress-fields-api#104]
Just a passing thought, based on success of contributor day and more to come. I am wondering if it makes sense to build out a contributor section on the readme. Maybe identify the difference between "team" vs "contributors"?

**Comment by sc0ttkclark** [comment]
Sounds good to me, anything to acknowledge or credit people involved would be great. And if we leverage the contributors we had from the 2017 repo then that list could be expanded further with those contributors too.
