### ISSUE TITLE
Some unsolicited feedback from my time with the REST API project

### ISSUE THREAD

**Issue by danielbachhuber** [sc0ttkclark/wordpress-fields-api#11]
I've been working the WP-API project since August. In hindsight, here are some things I wish we had done in advance:

1. Set a clear mission statement for the project. This will give clarity to the problem you're solving, what to say yes to, and what to say no to. You ideally want to avoid [crises of faith](https://github.com/WP-API/WP-API/pull/759#issuecomment-71595471) late in the project.
2. For your contributors, clarify involvement expectations. When most contributors are doing so in their "free" time (e.g. not getting paid directly for it), it's really difficult to budget for unlimited development scope. A little bit of proper project management goes a long way. I feel like WP-API is a much more sustainable project with four contributing developers than two. I would encourage you to have at least three.
3. Model your data before writing code. What is a field? What attributes should it have and why? What is a control? What attributes should it have and why? When you dive into development before appropriately modeling your application, you run into these implementation details one by one, and burn a lot of time (waiting to) discuss them.
4. Focus on clearing blockers above all else. Because you're working on an open source project with contributors across many timezones, average time to feedback will optimistically be 6 hours. More likely, it will be 24-48 hours. This slow feedback cycle can kill progress on pull requests. As a project maintainer, prioritize giving feedback, clearing blockers, and making decisions.

@rachelbaker @joehoyle or @rmccue may have other input.

**Comment by johnbillion** [comment]
Point 3 here is really important. My hope with the original Metadata/Metamorphosis project was that a great API would be designed first, but people were writing code before the first day's meeting was over.

I think if this project is going to be a success, the code needs to be put on hold while some higher level models are drawn up for the bigger picture.

**Comment by sc0ttkclark** [comment]
3 was a lot easier because we used the Customizer API as the base, it made modeling much easier before going into development. I did spend a bit of time modeling via php and faux code so I think I covered that pretty well. The issues from in the last project were unfortunate and this project started with a clean slate AND 10up has given me a ton of time on the clock to work on it at my leisure to get things right.

The unsolicited feedback above was definitely solicited :) Thank you to both of you for all of this, it reinforces the needs for everything you've outlined and I'm super glad I'm on the same page with you. I'm excited about this project and we're inching forward towards the next milestone with the core dev team reviewing it later this month.

**Comment by helenhousandi** [comment]
I agree that it's important that the modeling is documented **without code**. I had, for some reason, thought that this already existed somewhere (like a Google Doc), but I'm not finding it now. @sc0ttkclark - do you have this somewhere, or am I dreaming? Do you have what you need to work on this? I would put any other code decisions on hold until this is in place here in the repo.

**Comment by sc0ttkclark** [comment]
Yeah I'll go grab it and put it into the wiki?

**Comment by rmccue** [comment]
FWIW, I spent about a month solid just getting the initial API data design down before we had 0.1, so I agree with that. My only regret is that I didn't do the same for the internal API as well. :)

**Comment by helenhousandi** [comment]
My preference is in-repo in a docs directory or similar, probably Markdown files. Open to what other people think though, based on their experiences.

**Comment by sc0ttkclark** [comment]
@rmccue I totally get the reference in that last part :)

@helenhousandi I feel like wiki is better and the README.md can link off to the wiki for certain parts like examples etc, but we can always change it later. For now I'll go with the wiki since other projects make use of it that way too.

**Comment by sc0ttkclark** [comment]
Also FWIW, this is now the 7th time I've personally built this API. Not for the Fields API project, but for Pods and my other plugins and projects for work. I'll focus this week on filling the Wiki with good info from the initial project start at the start of the year.

**Comment by helenhousandi** [comment]
Here are my reasons for preferring in-repo:

* Accepts issues and PRs. The wiki is a Git repo, but has no exposed GitHub interface that I know of besides viewing.
* Does not largely inherently rely on another service (GitHub).

I am not worried about whether or not you know the material, I just want to make sure we have all the things in place that set us up for success and good, constructive feedback.

**Comment by danielbachhuber** [comment]
> Accepts issues and PRs. The wiki is a Git repo, but has no exposed GitHub interface that I know of besides viewing.

You could solve this by having the documentation in another repo. I think [this approach](https://github.com/WP-API/docs-v2) is working well for WP-API.

Having all of the docs in Markdown is good for portability.

**Comment by sc0ttkclark** [comment]
Closing this since it's got lots of valuable information and insight, but all the actionable things are in their own separate issues.
