### ISSUE TITLE
[4.0] Field (Control) Type classes

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#13]
Would love any help from contributors on suggestions for skeleton classes / methods that cover the following:

1. Sanitization of value before save
2. Override save of a value to a different place (for third party things)
3. Display field input for form
4. Enqueue assets (js/css) apart from field input display in above number 3, done in footer enqueue of page request

Other things that would be great to figure out, though I'm not sure how best to tackle it yet:
* Validation of value before the start of saving data
* Field value display (onto page in theme)

Registering them would look like this, that part is somewhat the easy part:

`$wp_fields->register_control_type( 'text', 'WP_Fields_API_Control_Text' );`

**Comment by sc0ttkclark** [comment]
@helenhousandi ideas here would be great too

**Comment by ihorvorotnov** [comment]
We already have some sanitization functions in core, shouldn't we use them? A hook at this place to modify the default validation would be nice.

<blockquote>Field value display (onto page in theme)</blockquote>

ACF uses own `get_field()` and `the_field()` functions, it's really easy to work with them. They can be looped through just like posts (repeaters and flexible fields). We can have smth like `get_meta_field()` / `the_meta_field()`. Basically, wrappers for `get_post_custom($post_id)` or a combination of `get_post_custom_keys()` and `get_post_custom_values()` - to have an assoc array and all fields, including non-unique. Or a custom query and assoc array in the end. Not sure what is better - using existing WP functions or working with DB directly. Also, we'll probably have serialized values for some fields, so we might also check for this and un-serialize. I'm currently checking all my past projects and trying to collect all possible use cases for the fields (and I'm extensively using postmeta on every single non-blog project). I've written some custom getters and setters for postmeta previously. Will see if there's something to borrow.

**Comment by sc0ttkclark** [comment]
Going to leave display to theme out here for the time being, but just committed all of the new contro ltype stuff overnight and throughout today. Going to close this one out for now.
