### ISSUE TITLE
Repeatable / Loop fields and groups

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#16]
This is just a placeholder, it exists for us to return to once we get more work done on the main field types. We want to ensure the Fields API enables plugin/theme developers to make use of their own custom implementations of a repeatable / loop field type. We aim to ensure a standard way to interact with the Fields API for such a purpose, leaving UI to the discretion of the plugin/theme developer for any given project.

**Comment by khromov** [comment]
Excellent initiative :+1:

**Comment by sc0ttkclark** [comment]
Related #8

**Comment by sc0ttkclark** [comment]
Closing in favor of tracking in #8
