### ISSUE TITLE
Very interesting!

### ISSUE THREAD

**Issue by paaljoachim** [sc0ttkclark/wordpress-fields-api#2]
Hey

I just got to say that this looks very interesting!

I would suggest posting about this in the Advanced WordPress Facebook group as a way for a lot of people to quickly find out about this project:
https://www.facebook.com/groups/advancedwp/
and a way to get some quick feedback.

I will also suggest posting in a LinkedIn WordPress group:
https://www.linkedin.com/grp/home?gid=1482937
https://www.linkedin.com/grp/home?gid=3722491

**Comment by sc0ttkclark** [comment]
Feel free to post about this project those places, I've got my hands full at the moment.

**Comment by paaljoachim** [comment]
Could you give me a short synopsis of the project in which I can post so that I get this right?
