### ISSUE TITLE
[4.0] Fatal error on install

### ISSUE THREAD

**Issue by ericandrewlewis** [sc0ttkclark/wordpress-fields-api#23]
I installed the plugin on WordPress 4.2 and overrode the core files with the files included in `implementation/`. This produced a fatal error.

`Fatal error: Class 'WP_Customize_Theme_Control' not found in /srv/www/wordpress-develop/src/wp-includes/class-wp-customize-manager.php on line 1378`

I believe this is because the overridden version of `class-wp-customize-control.php` does not include `class WP_Customize_Theme_Control` which was added in 4.2.

While we're at it, can we add installation instructions for the plugin as it is?

**Comment by sc0ttkclark** [comment]
I'm refreshing our customizer implementation with WP 4.3.x right now, it'll take a while but that'll resolve this and make Fields API only compatible with WP 4.3.x.

**Comment by sc0ttkclark** [comment]
Tests passing, fatals be gone!
