### ISSUE TITLE
Implementation: Widget forms

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#27]
- [x] Method to register config for widget form fields (return array?)
- [x] Widget form parent method should look for fields config, if set, output the form fields
- [x] Widget update parent method should look for fields config, if set, process saving of the form fields

**Comment by sc0ttkclark** [comment]
Need to assign to Nicholas when I get his username

**Comment by sc0ttkclark** [comment]
@nicholasio feel free to update the task list on this one

**Comment by nicholasio** [comment]
Ok, I'll look into this today and try to get some insights till monday

**Comment by sc0ttkclark** [comment]
Posting this here for posterity -- https://github.com/nicholasio/wordpress-fields-api/blob/implementation/widgets/implementation/widgets.php

**Comment by sc0ttkclark** [comment]
From @nicholasio:

> based on your user-fields implementations
> before outputting the controls, I’ll use the helper methods of the widgets class to define the name and the id's of the control, because this will make easier to save the data, as the data will come through $new_instance, and I’ll only need to sanitise the data

**Comment by sc0ttkclark** [comment]
@nicholasio 

I looked over your widget code and I think there’s some more things we can do:

1. Add a new class like WP_Widget_Fields_API or something, which extends the WP_Widget base class, so we can add some more object oriented code

2. saving / etc is now done in the user implementation, you can see that for what you need to do there

**Comment by nicholasio** [comment]
Initial PR here: #69
