### ISSUE TITLE
Implementation: User editor

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#29]
- [x] Sections = Headings
- [x] Display sections and their fields in user editor form, below contact fields
- [x] Save handling in editor
- [x] Pull values for fields based on user currently being editted
- [x] Merge existing user editor fields into implementation
- [x] Handle edit_user compatibility concerns
- [x] Get user object fields saving correctly (currently meta-only)
- [ ] Test it out, confirm all fields functional

Idea: Maybe hook into user insert / update function to process fields like for posts in #26?

**Comment by sc0ttkclark** [comment]
Would be cool if in my free time I could follow up with integration with https://wordpress.org/plugins/wp-user-profiles/screenshots/ so that if that plugin is active, we add our sections as meta boxes and display them on a specific tab.

**Comment by sc0ttkclark** [comment]
Here's what I've got so far:

https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/implementation/wp-admin/includes/class-wp-fields-api-user-profile.php

**Comment by nicholasio** [comment]
I'm not able to test this out, Is this ready for testing?

It appear you're trying to load a file that does not exist in the _wp_fields_api_user_edit_include() functions

```
require_once( WP_FIELDS_API_DIR . 'implementation/user-profile.php' );
```

**Comment by sc0ttkclark** [comment]
Almost ready for testing, I'm trying to clear out some of the remaining `@todo` markers in https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/implementation/wp-admin/includes/class-wp-fields-api-user-profile.php so I can move onto plugging it all in.
