### ISSUE TITLE
Implementation: Settings API

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#33]
- [ ] Map Settings API functions over to Fields API for backwards compat
- [x] Display sections
- [x] Display fields for each section
- [x] Settings save integration to process through Settings API
- [ ] Backwards compat control types?
- [ ] Extend (?) Control Type for Page Settings 
- [ ] Control "Group" to allow more than one type of control per "field". (e.g. thumbnail sizes)

**Comment by NateWr** [comment]
Is there any plan to support the tab pattern that seems to be widely adopted by WP plugins?

![tabs](https://cloud.githubusercontent.com/assets/2306629/10426721/b3699d5e-70da-11e5-91c6-7ed1eec22d67.png)

**Comment by sc0ttkclark** [comment]
#30 will allow for this type of behavior, though it won't be implemented in core (or at least hasn't been yet)

**Comment by NateWr** [comment]
:+1:

**Comment by holisticnetworking** [comment]
Question, in terms of WordPress' overarching strategy going forward:

My understanding has been that the Customizer was implemented, at least in part, as a means to eliminate other types of customization screens. My understanding was that they wanted everything to be eventually pushed over to the Customizer.

With this in mind, does updating the Settings API make sense? I'm only too happy to see this behemoth go the way of the dodo. But I'm just wondering if effort could be better-used in other areas?
