### ISSUE TITLE
Core Proposal for Merge into WP 4.6

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#35]
Just adding this here for later
- [ ] Look at previous Core Proposals and devise our markup / format from those

**Comment by paaljoachim** [comment]
Thoughts as to markup of a core proposal based on the oEmbed merge proposal as well as a few of the others below it. https://make.wordpress.org/core/tag/feature-plugins+merge+proposal/
I will shape it as question and answer. As it might be easier this way for shaping the merge proposal.
So you could just go ahead and answer the questions that would be great.

Can you give us a little of the history of the project?

What is the WP Fields API and why do we need it?

What about security concerns?

Browser compatibility?

How would this change core?

How would you add this to core?

Developer notes you can share?

What are some of the remaining issues / ongoing work?

What are the future plans for WP Fields API?

Contributors?


----

- A paragraph of the history of the project.
- A few sentences on who is involved.
- Purpose of the project. (What is the WP Fields API and why do we need it?)
- Goal.
- Security considerations.
- Browser compatibility
- Core changes & Merge implementation details
- Developer notes.
- Remaining issues/ongoing work.
- Future plans.
- Contributors

**Comment by cloudstoneme** [comment]
seems we can't expect it in 4.7?

**Comment by sc0ttkclark** [comment]
No, there we're some additional changes we wanted to make to the ease of use for developers along with some personal/professional obligations that limited my availability the past couple of months which were crucial to 4.6 features.

**Comment by cloudstoneme** [comment]
It's so sad, I've been expecting that fields api merge into WP core for a while, it's really annoying  when develop a plugin/theme with admin settings/options, even there is so many fields framework.

**Comment by sc0ttkclark** [comment]
Totally get that :( but with the latest changes we've been working on, I think it's ready for final proposal stage if it tests right and works as we've built and scoped.
