### ISSUE TITLE
REST API Support: Endpoints for Schema, Expose Fields to REST

### ISSUE THREAD

**Issue by Mte90** [sc0ttkclark/wordpress-fields-api#39]
Are there any plans for the rest API support?
- [ ] Create/Extend REST API Endpoints for Schema
- [x] Expose Fields to REST (register_rest_field)

**Comment by sc0ttkclark** [comment]
Yes, we need help working on extending the REST API endpoints that expose the fields available for a post type, user, etc

**Comment by danielbachhuber** [comment]
Related https://github.com/WP-API/WP-API/issues/1822, https://github.com/alleyinteractive/wordpress-fieldmanager/issues/407

**Comment by sc0ttkclark** [comment]
@danielbachhuber when using `register_rest_field`, should we register all fields or should we make that opt-in. The default is no get/update/schema callback right now.

https://github.com/sc0ttkclark/wordpress-fields-api/commit/c394e4f13fc54f659c28f19f69d98e14fe28c2ff

**Comment by danielbachhuber** [comment]
> should we register all fields or should we make that opt-in.

Good question. I'd imagine we'd want it to be opt-in, but that's not a strong opinion.

**Comment by diddledan** [comment]
I think if no preference is specified when a field is created then it should be exposed by default. That way if the developer who creates a new field is lazy she'll get out-of-the-box functionality via REST. The developer should be able, however, to choose to opt-out of REST support if they're going to implement their own interface.

**Comment by sc0ttkclark** [comment]
We're now somewhat mirroring some of the stuff from https://core.trac.wordpress.org/ticket/35658 and only using `register_rest_field` if `show_in_rest` is set.
