### ISSUE TITLE
[4.0] Post Type meta box priority

### ISSUE THREAD

**Issue by paulwilde** [sc0ttkclark/wordpress-fields-api#4]
In your example for ```fields_api_example_post_field_register()``` I believe the priority should be numeric based to keep the new API consistent rather than bowing down to what ```add_meta_box()``` did previously.

```add_meta_box()``` could then be changed to translate current low/high/core/default priorities into sane numeric default values to retain backwards compatibility.

**Comment by sc0ttkclark** [comment]
Assigning this to @helenhousandi, to get her feedback on using the same numeric priorities in the Fields API and instead add support to `add_meta_box` for numeric priorities, or adding a numeric to string conversion when interfacing with `add_meta_box` in the Fields API.

**Comment by helenhousandi** [comment]
I think numeric priorities are better to standardize on - they're much easier to remember and relate, more fine-grained, and more universally understandable. Meta boxes drive me crazy - which argument uses normal, and which one uses default?

**Comment by sc0ttkclark** [comment]
@helenhousandi so we should write up the fix on our side in the API or in add_meta_box separately to support numeric?

**Comment by sc0ttkclark** [comment]
We also may want to think about whether add_meta_box should be sitting on-top of WP_Fields_API_Section or not, there's a lot of benefit to be had with it doing that way I bet.

**Comment by helenhousandi** [comment]
To see where named contexts failed in core, see [r32707](https://core.trac.wordpress.org/changeset/32707) where we actually fixed sorting by those contexts, which has not functioned correctly since [r8712](https://core.trac.wordpress.org/changeset/8712) (which is to say: it has never functioned completely correctly). So, yes, there is probably some benefit to having those named contexts be aliases at some point :)

**Comment by Mte90** [comment]
I can't find `fields_api_example_post_field_register` and also use of `add_meta_box`.
Maybe this ticket need to be update?

**Comment by sc0ttkclark** [comment]
We're redoing the Post Editor implementation, it's not available as it was anymore but we need help with #1 so we can re-make these examples in an easier to understand way for new contributors and developers who want to try it out.

**Comment by sc0ttkclark** [comment]
Meta boxes are registered with their appropriate priority and meta box handling takes over the rest, however we should still follow up here to ensure those priorities are utilized when getting overall sort from get_sections etc.

**Comment by sc0ttkclark** [comment]
Added sorting compatibility when calling get_sections, get_controls, for meta box strings.
