### ISSUE TITLE
Call to undefined method WP_Customize_Manager::set_return_url() in /Applications/MAMP/htdocs/hndev/wp-admin/customize.php on line 28

### ISSUE THREAD

**Issue by holisticnetworking** [sc0ttkclark/wordpress-fields-api#40]
This error appears whenever I attempt to access the Customizer with the Fields API activated.

I have turned off all other plugins and gone back to twentyfifteen theme and still get this error. I've just pulled the latest changes from master and still get this error message.

Awesome ideas, though!! I've been trying to work on something like this for a while, based on my CakePHP experience with form building. Best of luck!

**Comment by sc0ttkclark** [comment]
Our Customizer implementation hasn't been updated with the latest WP 4.4 code, that'd probably be why :)

Will get to it through #25, assuming we still continue on with the Customizer implementation as a focus for our initial core inclusion.

**Comment by sc0ttkclark** [comment]
Closing this as maybe later, not sure if we're revisiting customizer implementation as it currently stands
