### ISSUE TITLE
add_setting() isn't really needed

### ISSUE THREAD

**Issue by paulwilde** [sc0ttkclark/wordpress-fields-api#5]
In your examples you include the ```add_setting()``` method for each object type. I believe having this as a requirement for each control is pretty pointless and would add a lot of unnecessary code when you compare it to how some third-party libraries handle stuff like this already.

Currently each object type has only 1 data storage:

Users - wp_usermeta
Post Types - wp_postmeta
Taxonomies - wp_termmeta (I'm guessing future tense here).
Settings - wp_options

Whereas the Customiser has 2 data storage options, theme mods and the wp_options table, hence the requirement for ```add_setting()```.

The API obviously isn't fleshed out yet, but this is the main thing that strikes me as something that would eventually become quite cumbersome, and would drive me to just create my own wrapper that would register the setting the same time as the control.

**Comment by sc0ttkclark** [comment]
After discussion with the Customizer team, there are reasons for Settings and Controls to be separated. However, I have adjusted the code to allow for registering the 'control' in the Field args (Settings were renamed to Fields in the Fields API code last week).
