### ISSUE TITLE
Should there be WYSIWYG Control/Fields?

### ISSUE THREAD

**Issue by ymazuz** [sc0ttkclark/wordpress-fields-api#50]
Seems like plugin devs might expect to be able to quickly add a WYSIWYG/TinyMCE editor to the backend using the Fields API. I don’t see a way to do so now. Apologies if I missed anything about it in the Issues or docs. But if it hasn’t already been discussed, are there any chances you’d be willing to add it? I think it makes sense in core instead of being left to 3rd parties.

**Comment by sc0ttkclark** [comment]
I don't see why not, honestly this should already be in there but it's not :)

Feel free to chip in via a PR, add a new control type at implementation/wp-includes/fields-api/control-types/class-wp-fields-api-wysiwyg-control.php and base it on the one for textarea, just use wp_editor() instead.

**Comment by ymazuz** [comment]
Thanks for the super fast response. Was just about to add that if you do keep this open I probably won’t be making a PR anytime soon. I tried something similar by subclassing the WooCommerce Settings API a few months ago and got nowhere. But I’ll keep my eye on this and if nobody else has gotten around to it, maybe I’ll take a crack at it eventually!

**Comment by sc0ttkclark** [comment]
If it takes you longer than 10 minutes, bill me :)

**Comment by ymazuz** [comment]
Ok if it’s that easy, I’ll try it in the next few days!

**Comment by sc0ttkclark** [comment]
Hop into Slack #core-fields if you need any help whatsoever, I pledge my unending support to you :)

**Comment by ymazuz** [comment]
Sweet. I got it to display a tinyMCE box, but um, it’s missing all the buttons except Add Media (and other ones added by 3rd party plugins). And the text is white on white. So, yeah, no PR yet. But I’m in Slack now as @ yonatron.
