### ISSUE TITLE
Idea - Fields for Quick Edit panels

### ISSUE THREAD

**Issue by ihorvorotnov** [sc0ttkclark/wordpress-fields-api#6]
Getting the fields via core API in post edit screen is cool, ACF and a horde of similar plugins already do this even without API. But there's almost no solutions for adding custom fields to the Quick Edit panels. Being able to add fields there would help many users. Maybe, it's out of scope for this API. Maybe it's too early to think about it. Maybe we need a total rework of Quick Edit panels. That's kind of terra incognita atm. Just saying.

**Comment by sc0ttkclark** [comment]
Quick edit needs love, for sure, definitely something for later

**Comment by KingYes** [comment]
+1

**Comment by sc0ttkclark** [comment]
Closing this and assigning "maybe later" label to revisit, don't worry, we can reopen when the timing is right.
