### ISSUE TITLE
Change Object Name to Object Subtype

### ISSUE THREAD

**Issue by diddledan** [sc0ttkclark/wordpress-fields-api#63]
I still think it's confusing to have `object_type` and `object_name` when the latter is determined to possibly be a `post_type`.

"so my name is the type, and the type is the name, but sometimes the type is the name and the name is the type? my brain hurts.."

**Comment by sc0ttkclark** [comment]
Post types are object names, Taxonomies are object names, open to ideas here on improving this.

**Comment by diddledan** [comment]
an `object` in my opinion is the individual post or term or...

so the `object_type` would be whatever `_type` fits the role of the current `object` be that taxonomy slug or post type slug or ...

then we need to differentiate `object_type`s own typing to "term" or "post" so that we target the right screen, so something along the lines of `meta_object_type`?

that would leave us with
`object` => the individual post or term or ..
`object_type` => the slug of the post's cpt or the term's taxonomy
`meta_object_type` => the type of aggregation of items of `object_type` such as `post` or `term`.

**Comment by diddledan** [comment]
an alternative could be rename object_type to `group_type` (term or post or ..) and replace object_name with `object_type` (slug of cpt or tax or..).

**Comment by diddledan** [comment]
there we go, how about:

`object_type`,
`object_group`

where object_type is the slug of cpt or tax, and the object_group is `post` or `term`?

**Comment by sc0ttkclark** [comment]
As per our discussion in Slack, we're going to go with Subtype as it's immediately apparent that is a perfect name for this type of term.

https://wordpress.slack.com/archives/core-fields/p1456777324000308

I'll work on a PR for this.

**Comment by sc0ttkclark** [comment]
Fixed by https://github.com/sc0ttkclark/wordpress-fields-api/pull/67 which renamed Object name to Object subtype
