### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by danielbachhuber** [sc0ttkclark/wordpress-fields-api#7]
A project of this complexity would blossom with a great deal of test coverage and some continuous integration.

**Comment by sc0ttkclark** [comment]
Much sense, you make

**Comment by sc0ttkclark** [comment]
:-D

Any ideas on how to kickstart tests? I can help for sure, just need not to be the only one working on it. Also are you aware of any unit tests for the Customizer?

**Comment by danielbachhuber** [comment]
> Any ideas on how to kickstart tests?

I'll need to spend a bit of time diving into the architecture. I'm personally a fan of integration-esque tests, which cover expected business cases. For fields generally, I'd think this to be two-fold:

1. Does the field render as expected?
1. When I submit the form, does the data get saved appropriately?

For the latter, more standard PHPUnit tests could work.

For the former, you'd essentially register every possible variant of a how a field could be registered, and then add test coverage confirming output. Fieldmanager does [some awkward regex pattern matching](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/tests/php/test-fieldmanager-autocomplete-field.php#L40). Internally at Fusion, we're using [Query Path](https://github.com/technosophos/querypath) for writing tests with jQuery-style selectors:

```
public function setUp() {
	parent::setUp();
	$this->user = Fusion_User_Generator::create_user_generator()->generate_author();
	wp_update_user( array( 'ID' => $this->user->get_id(), 'display_name' => 'Fidel Martinez' ) );
}

public function test_rel_canonical() {
	$dom = $this->get_view_output_as_dom( $this->user->get_permalink() );
	$this->assertEquals( $this->user->get_permalink(), qp( $dom, 'head link[rel="canonical"]' )->attr( 'href' ) );
}
```

It may work well for your needs. It's close to open-sourceable — I just haven't gotten around to it because @tollmanz hasn't kicked me hard enough.

However, because we care about how the JS works, we're currently evaluating [mocha-phantomjs](https://github.com/metaskills/mocha-phantomjs) (which would stray into the JS territory).

**Comment by tollmanz** [comment]
![sf2hf-ryu-axe](https://cloud.githubusercontent.com/assets/921795/7893251/b1b6e938-0610-11e5-8272-8cc1ee2745a5.gif)

**Comment by sc0ttkclark** [comment]
Copying tests structure from https://github.com/WP-API/WP-API :)

So far, looking good, I'm making the first test case right now for the main add / get methods.

**Comment by sc0ttkclark** [comment]
Got full test coverage with the main get / add / remove methods in WP_Fields_API for containers, screens, sections, fields, and controls. Will do more later too.

**Comment by Ramoonus** [comment]
I`m here
