### ISSUE TITLE
Understanding WP_Fields_API_Form::register and add_form

### ISSUE THREAD

**Issue by tlovett1** [sc0ttkclark/wordpress-fields-api#72]
After reading all the documentation I don't understand how to register a new form from scratch. I want to add an example to the repo of creating a simple form to manage a couple fields stored in options. Do I need to create a new class extending `WP_Fields_API_Form`? Can I just use `add_form`? Does `add_form` simply instantiate a form that has already been registered?

**Comment by sc0ttkclark** [comment]
For all of the core implementations, I've chosen to encapsulate them into their own classes to keep organization concise.

However, this doc page explains how to add forms and do things manually:

https://github.com/sc0ttkclark/wordpress-fields-api/blob/develop/docs/registering-fields.md

The use of [WP_Fields_API_Form_Post](https://github.com/sc0ttkclark/wordpress-fields-api/blob/develop/implementation/wp-includes/fields-api/forms/class-wp-fields-api-form-post.php) (and others) can be seen in the main loading function that includes the form configs in https://github.com/sc0ttkclark/wordpress-fields-api/blob/develop/wordpress-fields-api.php#L85-L88 -- which happens during the `fields_register` action.

**Comment by tlovett1** [comment]
I think we need to scrap `::register_form` seems like it is an over-complication when we have `add_form`.

**Comment by sc0ttkclark** [comment]
I'm thinking about what that might look like, what changes it'd require etc. We can chat more about this in today's meeting if you'd like.

**Comment by tlovett1** [comment]
I'm crafting a PR for this and some other stuff.
