### ISSUE TITLE
What is the purpose of object type/subtype?

### ISSUE THREAD

**Issue by tlovett1** [sc0ttkclark/wordpress-fields-api#73]
What do we need object types and subtypes for? How do these affect the registration of fields/sections/forms?

**Comment by tlovett1** [comment]
It seems like we are overcomplicating by storing forms like so: `$forms[$object_type][$object_sub_type][$id]`. In order to get a form you need to know type/subtype which seems unnecessary.

**Comment by sc0ttkclark** [comment]
Removed object type / object sub type usage for getting forms, adding form still has you set object type.

Adding sections and controls no longer requires object type / sub type either.

Adding fields requires object type (when not adding the field in the context of a control object which already has an object type set for the parent section's form).

Object types define Post vs Term vs User vs Custom for purposes of saving data for that form and the object type of all fields on the controls for that form.

Object sub types define additional information that can further limit visibility of a section or control through logic checks in implementation.
