### ISSUE TITLE
Add global `fields_get_{$object_type}` filter

### ISSUE THREAD

**Issue by felixarntz** [sc0ttkclark/wordpress-fields-api#80]
For updating, there is an action `fields_update_{$object_type}` which makes it easy to implement updating a value for a custom object type. However, there is no such global filter for retrieving a value, so in order to globally implement this functionality for a custom object type, I would need to hook my function into dozens of filters which would be a pain to do.

Therefore I'm proposing to introduce a global filter `fields_get_{$object_type}`, passing the default value, the item ID and the field object itself.

**Comment by sc0ttkclark** [comment]
Added in #81
