### ISSUE TITLE
Do you have a road map?

### ISSUE THREAD

**Issue by colomet** [sc0ttkclark/wordpress-fields-api#84]
Do you have an idea about when the beta will be released?

thanks

**Comment by sc0ttkclark** [comment]
Here's the most recent progress update which includes what's left in each area:
https://github.com/sc0ttkclark/wordpress-fields-api/blob/develop/docs/progress.md

I'm not sure we can go beta until we get some more solid backing from core contributors to ensure we're going the right direction.

**Comment by lukecav** [comment]
A couple of Fields API mentions in this Gutenberg issue. https://github.com/WordPress/gutenberg/issues/3304

**Comment by sc0ttkclark** [comment]
Just noticed that, thanks! Yeah if people built their stuff in Fields API and Gutenberg just slurped the Fields API config for it's purposes, that'd be just about the best thing in the whole entire world.

**Comment by rpkoller** [comment]
I've posted an issue over at the Gutenberg issue tracker as well a while back in the same vein: https://github.com/WordPress/gutenberg/issues/2718 ( but so far still unsure "what" to answer )

**Comment by lukecav** [comment]
Again another mention on. 
https://github.com/WordPress/gutenberg/issues/3390

**Comment by sc0ttkclark** [comment]
Yep saw that, thanks Luke!

**Comment by citelao** [comment]
I want to hop on this that I started work (6 months ago) on a [Composer package implementation](https://github.com/sc0ttkclark/wordpress-fields-api/pull/91) for this API so people can start including beta versions in their own plugins.

I've hit some roadblocks in the implementation, but there's definitely a plugin-developer-facing path forward in addition to any Core proposals.
