### ISSUE TITLE
Rules to set visibility of sections and fields based on page template, post category, and more

### ISSUE THREAD

**Issue by nickcernis** [sc0ttkclark/wordpress-fields-api#9]
Advanced Custom Fields and similar plugins offer rules for meta box visibility such as these:

![add_new_field_group_ _my_blog_ _wordpress](https://cloud.githubusercontent.com/assets/647669/7855509/2a7def26-051a-11e5-9e6f-1a8fbf976a93.jpg)

This is very powerful because it allows the creation of meta boxes that:

- appear only when you select a certain page template (meta boxes appear as soon as you select the template, without a page refresh);
- appear only for certain post categories
- etc.

To accomplish this, there are a couple of approaches we could take:

1. Let the first parameter of the `add_field` and `add_section` methods take an optional array instead of the default string, which would allow users to specify in more detail exactly where fields and sections appear.

2. Add an additional 'visibility' parameter that would work alongside 'capability' to allow users to filter areas where fields would appear. (This may be more legible than option one.)

I appreciate that the Fields API may not be a complete functional replacement for ACF. But if it's to become widely adopted and loved by all, it probably needs to take on some of the more advanced functionality that developers are currently gaining from third-party plugins.

**Comment by danielbachhuber** [comment]
Fieldmanager has a similar `display_if`attribute. The logic is such that the field will display if the value of another field is N.

**Comment by helenhousandi** [comment]
The aim as far as plugins are concerned is not to replace plugins like ACF - it's to enable those plugins that provide more complex UI and/or UI builders for fields to use a common API. The project in its current status is rightfully focusing on the PHP side of the API, and I would not endorse the inclusion of this functionality via UI in core itself.

**Comment by sc0ttkclark** [comment]
Definitely what I was about to say @helenhousandi :)

I will make every effort to ensure something like this will be easy to hook into for plugin purposes though, so anyone with a vested interest feel free to follow up on this.

**Comment by pimschaaf** [comment]
Just to clarify, in the above comments at least two types of visibility dependencies are discussed. ACF discerns the two as `Custom location rules` and `Conditional Logic`. 

Drawing a parallel between ACF and WP Fields API I think the first would apply to 
`$wp_fields->add_section`, while the second would apply to `$wp_fields->add_field`.

Custom location rules are discussed above by @nickcernis. In addition, Conditional Logic works based on the values of 'sibling' fields (i.e. fields that are in the same section).

References:
http://www.advancedcustomfields.com/resources/custom-location-rules
http://www.advancedcustomfields.com/resources/field-settings/ (it appears little documentation is available for ACFs Conditional Logic)

**Comment by nickcernis** [comment]
Thanks for the feedback, @helenhousandi and @sc0ttkclark!

To clarify, I wasn't proposing that this be added via a new UI – I was suggesting that it be possible without a lot of additional code via the new API.

**Comment by sc0ttkclark** [comment]
Then request granted :)
